# Thông tin sinh viên

**Họ tên**: Dương Trường Bình

**MSSV**: 21127229

# Phép khử Gauss - Jordan

**Phép khử Gauss - Jordan** là một cách biến đổi tương đương dòng đưa ma trận về ma trận đường chéo. Thuật giải gồm các bước:

Thực hiện các bước sau cho cột thứ i, i=1,2,...n

> **Bước 1**. Kiểm tra các số hạng từ dòng i đến dòng n của cột thứ i. Nếu chúng gồm toàn số 0, kết luận ma trận A không khả nghịch và giải thuật chấm dứt. Ngược lại, đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới dòng thứ j về dòng thứ i.

> **Bước 2**. Với số hạng ở dòng thứ i là $a\neq 0$ , nhân dòng i với 
$\frac 1 a$
 để nhận được số **1** (nằm trên đường chéo của A).
 
> **Bước 3**. Cộng một bội số thích hợp của dòng i với các dòng khác dòng i để biến các số hạng trên cột i về số **0** (trừ số hạng nằm ở dòng i. Trở lại bước 1 cho dòng kế, i = i + 1.

Kết thúc giải thuật , ta nhận được ma trận $(I_n|A^{-1})$


In [10]:
def printSystemOfEquations(matrix):
    m = len(matrix)
    n = len(matrix[0])
    
    print('[', end='')
    for i in range(m):
        if i != 0:
            print(' ', end='')
        print('[', end='')
        for j in range(n):
            print(f'{matrix[i][j]:5.2f}', end=' ')
        print(']', end='')
        if i < m - 1:
            print()
    print(']')
    print()


def permuteRow(matrix, i, j):
    matrix[i], matrix[j] = matrix[j], matrix[i]

In [11]:
def inverse(matrix):

    size = len(matrix)

    matrix = [matrix[i] + [1 if i ==
                           j else 0 for j in range(size)] for i in range(size)]

    for index in range(size):

        if matrix[index][index] == 0:
            for i in range(index + 1, size):
                if matrix[i][index] != 0:
                    permuteRow(matrix, i, index)
                    break

            else:
                index += 1

        factor = matrix[index][index]
        matrix[index] = [i / factor for i in matrix[index]]

        for i in range(size):
            if i != index:
                matrix[i] = [matrix[i][j] - matrix[i][index] *
                             matrix[index][j] for j in range(size * 2)]

    result = [row[size:] for row in matrix]

    return result

In [12]:
test1=[
    [1,3,2,1],
    [0,1,-1,-1],
    [0,0,1,3],
    [0,0,0,1]
]
test2=[
    [1,-1,0],
    [2,1,-1],
    [0,1,1]
]
test3=[
    [1,2],
    [3,4]
]
result=inverse(test1)
printSystemOfEquations(result)


[[ 1.00 -3.00 -5.00 11.00 ]
 [ 0.00  1.00  1.00 -2.00 ]
 [ 0.00  0.00  1.00 -3.00 ]
 [ 0.00  0.00  0.00  1.00 ]]



## Ý tưởng thực hiện

Sử dụng thuật toán Guass-Jordan để tìm ma trận nghịch đảo.

1. **Ghép ma trận đơn vị**: Ghép ma trận đơn vị vào ma trận ban đầu để tạo thành một ma trận mở rộng. Mỗi dòng của ma trận đơn vị sẽ có giá trị 1 tại chỉ số đúng hàng của nó và 0 ở các chỉ số còn lại.

2. **Biến đổi Gauss-Jordan**: Sử dụng biến đổi Gauss-Jordan để biến đổi thành ma trận đường chéo.
   - Xác định phần tử pivot: Với mỗi cột, xác định phần tử pivot. Nếu phần tử pivot bằng 0, tìm dòng khác có phần tử khác 0 để hoán vị hai dòng. Nếu không tìm được dòng nào khác không thì kết luận ma trận không khả nghịch và kết thúc giải thuật.
   - Chia cả dòng cho phần tử pivot: Chia dòng cho giá trị của phần tử pivot để đưa pivot về giá trị 1.
   - Biến đổi các dòng còn lại: Thực hiện biến đổi để đưa các số hạng trên cùng cột của các dòng khác về 0.

3. **Trả về ma trận nghịch đảo**: Lấy các cột bên phải của ma trận sau khi đã hoàn thành các biến đổi.

# Mô tả các hàm

## printSystemOfEquations

- **Input**:
    - matrix: Ma trận mở rộng đầu vào
- **Output**: None
- **Mục đích**: In ra ma trận mở rộng được căn chỉnh cho dễ nhìn
- **Hoạt động**: Lặp qua từng phần tử và in ra nó

## permuteRow

- **Input**:
    - matrix: Ma trận mở rộng đầu vào
    - i,j: Thứ tự của 2 dòng cần đổi chỗ
- **Output**: None
- **Mục đích**: Đổi chỗ hai dòng i và j của ma trận mở rộng
- **Hoạt động**: Dùng cú pháp của python để đổi chỗ hai dòng của ma trận

## inverse

- **Input**:
    - matrix: Ma trận vuông đầu vào
- **Output**: Ma trận nghịch đảo từ ma trận vuông đầu vào hoặc thông báo ma trận không khả nghịch
- **Mục đích**: Tìm ma trận nghịch đảo của ma trận vuông đầu vào
- **Hoạt động**:
    - Ghép ma trận đơn vị vào ma trận vuông đầu vào để tạo thành ma trận mở rộng
    - Biến đổi Gauss-Jordan
        + Xác định phần tử pivot: Với mỗi cột, xác định phần tử pivot. Nếu phần tử pivot bằng 0, tìm dòng khác có phần tử khác 0 để hoán vị hai dòng. Nếu không tìm được dòng nào khác không thì kết luận ma trận không khả nghịch và kết thúc.
        + Chia cả dòng cho phần tử pivot: Chia dòng cho giá trị của pivot để đưa pivot về giá trị 1.
        + Biến đổi các dòng còn lại: Thực hiện biến đổi để đưa các số hạng trên cùng cột của các dòng khác về 0.
    - Trả về ma trận nghịch đảo bằng cách lấy các cột bên phải của ma trận sau khi đã hoàn thành các biến đổi.



# Mở rộng hàm/ phương thức của các thư viện khác


In [13]:
import numpy as np

# Ma trận ban đầu
matrix = np.array([
    [1,3,2,1],
    [0,1,-1,-1],
    [0,0,1,3],
    [0,0,0,1]
]
)

# Tính nghịch đảo ma trận
inverse_matrix = np.linalg.inv(matrix)

print("Ma trận ban đầu:")
print(matrix)

print("Ma trận nghịch đảo:")
print(inverse_matrix)

Ma trận ban đầu:
[[ 1  3  2  1]
 [ 0  1 -1 -1]
 [ 0  0  1  3]
 [ 0  0  0  1]]
Ma trận nghịch đảo:
[[ 1. -3. -5. 11.]
 [ 0.  1.  1. -2.]
 [ 0.  0.  1. -3.]
 [ 0.  0.  0.  1.]]


In [14]:
import numpy as np
from scipy.linalg import inv

# Ma trận ban đầu
matrix = np.array([
    [1,3,2,1],
    [0,1,-1,-1],
    [0,0,1,3],
    [0,0,0,1]
])
# Tính nghịch đảo ma trận
inverse_matrix = inv(matrix)

print("Ma trận ban đầu:")
print(matrix)

print("Ma trận nghịch đảo:")
print(inverse_matrix)

Ma trận ban đầu:
[[ 1  3  2  1]
 [ 0  1 -1 -1]
 [ 0  0  1  3]
 [ 0  0  0  1]]
Ma trận nghịch đảo:
[[ 1. -3. -5. 11.]
 [ 0.  1.  1. -2.]
 [ 0.  0.  1. -3.]
 [ 0.  0.  0.  1.]]


In [15]:
import sympy as sp

# Ma trận ban đầu
matrix = sp.Matrix([
    [1,3,2,1],
    [0,1,-1,-1],
    [0,0,1,3],
    [0,0,0,1]
])

# Tính nghịch đảo ma trận
inverse_matrix = matrix.inv()

print("Ma trận ban đầu:")
print(matrix)

print("Ma trận nghịch đảo:")
print(inverse_matrix)


Ma trận ban đầu:
Matrix([[1, 3, 2, 1], [0, 1, -1, -1], [0, 0, 1, 3], [0, 0, 0, 1]])
Ma trận nghịch đảo:
Matrix([[1, -3, -5, 11], [0, 1, 1, -2], [0, 0, 1, -3], [0, 0, 0, 1]])


## So sánh kết quả

In [16]:
import numpy as np
from scipy.linalg import inv as scipy_inv
import sympy as sp

# Ma trận khả nghịch
matrix_invertible = np.array([[1, 2], [3, 4]])

# Ma trận không khả nghịch
matrix_non_invertible = np.array([[1, 1], [2, 2]])


# Sử dụng NumPy
try:
    numpy_inverse_invertible = np.linalg.inv(matrix_invertible)
except np.linalg.LinAlgError as e:
    numpy_inverse_invertible = None

try:
    numpy_inverse_non_invertible = np.linalg.inv(matrix_non_invertible)
except np.linalg.LinAlgError as e:
    numpy_inverse_non_invertible = None

# Sử dụng SciPy
try:
    scipy_inverse_invertible = scipy_inv(matrix_invertible)
except np.linalg.LinAlgError as e:
    scipy_inverse_invertible = None

try:
    scipy_inverse_non_invertible = scipy_inv(matrix_non_invertible)
except np.linalg.LinAlgError as e:
    scipy_inverse_non_invertible = None

# Sử dụng SymPy
sympy_matrix_invertible = sp.Matrix(matrix_invertible)
sympy_inverse_invertible = sympy_matrix_invertible.inv()

sympy_matrix_non_invertible = sp.Matrix(matrix_non_invertible)
try:
    sympy_inverse_non_invertible = sympy_matrix_non_invertible.inv()
except sp.matrices.common.NonInvertibleMatrixError as e:
    sympy_inverse_non_invertible = None

# In kết quả
print("Trường hợp ma trận khả nghịch:")
print("Thuật toán:")
printSystemOfEquations(inverse(matrix_invertible.tolist()))
print("NumPy:")
print(numpy_inverse_invertible)
print("SciPy:")
print(scipy_inverse_invertible)
print("SymPy:")
print(sympy_inverse_invertible)

print("Trường hợp ma trận không khả nghịch:")
print("Thuật toán:")
print(inverse(matrix_non_invertible.tolist()))
print("NumPy:")
print(numpy_inverse_non_invertible)
print("SciPy:")
print(scipy_inverse_non_invertible)
print("SymPy:")
print(sympy_inverse_non_invertible)


Trường hợp ma trận khả nghịch:
Thuật toán:
[[-2.00  1.00 ]
 [ 1.50 -0.50 ]]

NumPy:
[[-2.   1. ]
 [ 1.5 -0.5]]
SciPy:
[[-2.   1. ]
 [ 1.5 -0.5]]
SymPy:
Matrix([[-2, 1], [3/2, -1/2]])
Trường hợp ma trận không khả nghịch:
Thuật toán:
Ma trận không khả nghịch
None
NumPy:
None
SciPy:
None
SymPy:
None


- Vậy có thể thấy 3 thư viện NumPy, SciPy, SymPy và thuật toán ở trên
    - Đều có hàm để tìm ma trận nghịch đảo và ra kết quả giống nhau.
    - Tuy nhiên, thư viện NumPy, SciPy, SymPy trong trường hợp ma trận không khả nghịch sẽ báo lỗi còn thuật toán ở trên sẽ in ra thông báo và trả về None.