In [28]:
import random
import numpy as np

In [36]:
def inner(vector1,vector2):
    return sum([v1*v2 for (v1,v2)in zip(vector1,vector2)])
def norm(vector):
    return sum([i*i for i in vector])**(1/2)
def col(matrix,i):
    return [row[i] for row in matrix]
def create_vector(n):
    return [random.randint(0,n) for _ in range(n)]
def unit_vector(vector):
    return [i/norm(vector) for i in vector]
def norm_m(vector,m):
    return sum([i**m for i in vector])**(1/m)
def create_matrix(n,m):
    return [[random.randint(0,n*m) for _ in range(m)] for _ in range(n)]
def tranpose(matrix):
    return [[row[i] for row in matrix]for i in range(len(matrix))]
def dot(a,b):
    return [[inner(a[i],col(b,j)) for j in range(len(b[0]))] for i in range(len(a))]

In [8]:
matrix=[
    [1,2,3],
    [4,5,6]
]
print(col(matrix,1))

[2, 5]


In [21]:
a=[1,1,1]
b=[2,1,1]
print(inner(a,b))
print(norm(a))
print(norm_m(a,2))

4
1.7320508075688772
1.7320508075688772


In [16]:
print(create_vector(3))

[1, 3, 0]


In [19]:
print(unit_vector([3,4]))

[0.6, 0.8]


In [27]:
print(create_matrix(2,2))

[[3, 2], [2, 0]]


In [37]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
unit=[[1,0,0],[0,1,0],[0,0,1]]
Q, R = np.linalg.qr(A)
print(Q)
print(R)

[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [34]:
print(tranpose(A))

[[12, 6, -4], [-51, 167, 24], [4, -68, -41]]


In [38]:
print(dot(A,unit))

[[12, -51, 4], [6, 167, -68], [-4, 24, -41]]


In [39]:
print(dot(tranpose(Q),Q))
print(dot(Q,tranpose(Q)))


[[1.0000000000000002, -2.0816681711721685e-17, -5.551115123125783e-17], [-2.0816681711721685e-17, 0.9999999999999999, 2.7755575615628914e-17], [-5.551115123125783e-17, 2.7755575615628914e-17, 1.0]]
[[1.0000000000000002, 8.847089727481716e-17, 0.0], [8.847089727481716e-17, 0.9999999999999998, -3.469446951953614e-17], [0.0, -3.469446951953614e-17, 1.0]]
